repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict


  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff
        name: ruff-imports
        files: ^popupsim/backend/
        args: [--fix, --select, I, --exit-non-zero-on-fix]
      - id: ruff
        name: ruff-lint
        files: ^popupsim/backend/
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        files: ^popupsim/backend/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        files: ^popupsim/backend/(src|tests)/
        args: [--show-error-codes, --no-error-summary, --show-column-numbers]
        additional_dependencies: [pandas, pydantic, pandas-stubs, pylint-pydantic, babel, typer, simpy, matplotlib]

  - repo: https://github.com/pycqa/pylint
    rev: v3.3.8
    hooks:
      - id: pylint
        files: ^popupsim/backend/src/
        additional_dependencies: [pandas, pydantic, pandas-stubs, pylint-pydantic, babel, typer, simpy, matplotlib]